; Exercise actual scheduler at the supported 5 s negative ramp setting.
; Host sleep scheduling is slower than ESC ticks, so bound the wait by 10 s.
(sleep 0.2)
(test-check (= (ride-set-park 0) 0) "maximum ramp scenario exits healthy PARK")
(setq host-rx 0)
(setq host-adc1 1.0)
(sleep 0.9)
(test-check (and (= rv-armed 1) (> brk-rel 0.99) (= (ramp-neg) 5.0))
            "maximum ramp begins with armed reverse and full brake")
(setq host-adc1 0.0)
(setq host-adc0 0.4)
(sleep 0.2)
(test-check (and (> brk-rel 0) (= rv-dir 0) (= (ride-safety-state) 2)
                 (eq host-current-kind 'brake))
            "5s setting intentionally keeps brake active briefly after release")
(def host-decay-start (systime))
(loopwhile (and (> brk-rel 0.001) (< (secs-since host-decay-start) 10.0))
    (sleep 0.02))
(sleep 0.1)
(test-check (and (<= brk-rel 0.001) (eq host-current-kind 'absolute)
                 (< host-current 0) (= host-current-delay 0.2)
                 (= rv-dir -1) (= (ride-safety-state) 3)
                 (= safety-fault 0))
            "maximum supported brake ramp eventually hands control to reverse current")
(print (list 'maximum-ramp-release brk-rel host-current-kind host-current
             'host-elapsed-after-initial-200ms (secs-since host-decay-start)))
(test-finish)
