(sleep 0.2)
(test-check (= rm-rev-en 1) "RX startup fixture loads enabled reverse from EEPROM")
(test-check (and host-rx-configured (= host-rx-read-count 0) (= rv-seen 0))
            "RX configured while first input sample remains pending")
(print (list diag-first safety-fault (ride-safety-state) diag-at
             diag-tx-age diag-rx-age diag-motor-age))
(test-check (= rv-hw-ok 0) "RX readiness remains false before first completed read")
(test-check (and (= diag-first 0) (= safety-fault 0) (= motor-live 1))
            "uninitialized RX does not falsely trip the first motor iteration")
(test-check (= (ride-set-park 0) 0) "pending RX startup leaves healthy forward PARK exit available")
(setq host-adc1 0.8)
(setq host-rx 0)
(sleep 0.25)
(test-check (and (= rv-armed 0) (= rv-seen-release 0) (not (= rv-dir -1)))
            "holding brake and unread RX cannot arm reverse")
(setq host-rx-release t)
(sleep 0.15)
(test-check (and (= rv-hw-ok 1) (> rv-seen 0) (< (secs-since rv-seen) 0.1))
            "first successful RX sample publishes readiness with fresh heartbeat")
(test-check (and (= diag-first 0) (= safety-fault 0))
            "RX startup completion leaves no sticky false fault")
(test-check (and (= rv-armed 0) (= rv-seen-release 0))
            "button held from startup still needs release before reverse can arm")
(setq host-rx 1)
(sleep 0.15)
(test-check (and (= rv-seen-release 1) (= rv-armed 0))
            "first debounced release is recognized without arming reverse")
(setq host-rx 0)
(sleep 0.5)
(test-check (= rv-armed 1)
            "subsequent press and deliberate brake hold can authorize reverse")
(test-finish)
