; Appended separately to each fresh-VM fault scenario by the Python runner.
(test-check (= diag-first host-expected-cause) "captures the first recorded guard cause")
(test-check (and (= safety-fault 12) (= park-on 1) (= host-current 0)
                 (= (ride-safety-state) 5))
            "diagnostics preserve fault12 PARK zero-output and FAULT state")
(setq host-adc-type 0)
(setq host-range-ok t)
(test-check (= (ride-set-park 0) 12) "diagnostic fault still refuses PARK exit")
(send (test-event-pid) (cons 'event-data-rx [0x56 0x50 0x02 12 11 0 0 3 232]))
(sleep 0.05)
(test-check (= current-profile 0) "diagnostic fault still refuses UI mode change")
(def host-saved-at diag-at)
(def host-saved-tx diag-tx-age)
(def host-saved-rx diag-rx-age)
(def host-saved-motor diag-motor-age)
(test-check (and (>= diag-tx-age 0) (>= diag-rx-age 0) (>= diag-motor-age 0)
                 (< (secs-since diag-at) 5.0))
            "first-fault time and ages form a valid snapshot")
(sleep 0.05)
; A subsequent different fault must neither overwrite the cause nor its ages.
(diag-trip (if (= host-expected-cause 6) 3 6))
(test-check (= diag-first host-expected-cause) "first cause survives a later different fault")
(test-check (and (= diag-at host-saved-at) (= diag-tx-age host-saved-tx)
                 (= diag-rx-age host-saved-rx) (= diag-motor-age host-saved-motor))
            "first-fault timestamp and worker ages remain immutable")
(setq host-adc0 0.8)
(sleep 0.05)
(test-check (and (= safety-fault 12) (= park-on 1) (= host-current 0))
            "recovered inputs and held throttle cannot clear diagnostic fault")
(test-finish)
