(sleep 0.2)
(setq host-rx-fail t)
(setq host-rx-release t)
; Trapped child exit wakes parent; measure elapsed time rather than one sleep.
(def host-wait-start (systime))
(loopwhile (< (secs-since host-wait-start) 0.3) (sleep 0.01))
(test-check (= host-rx-read-count 0) "failed first read never supplies an RX sample")
(test-check (and (= rv-hw-ok 0) (= rv-seen 0))
            "failed first RX read stays unsupported rather than falsely ready")
(test-check (and (= safety-fault 0) (= diag-first 0) (= motor-live 1))
            "unsupported RX does not kill forward mode with a stale-zero fault")
(test-check (= (ride-set-park 0) 0) "unsupported RX preserves healthy forward PARK exit")
(test-check (and (= rv-armed 0) (not (= rv-dir -1)))
            "failed RX startup never arms reverse")
(test-finish)
