(sleep 0.2)
(setq host-rx-release t)
(sleep 0.15)
(test-check (and (> host-rx-read-count 0) (= rv-hw-ok 1) (> rv-seen 0))
            "RX stale scenario first completes real monitor reads")
(test-check (and (= diag-first 0) (= safety-fault 0))
            "RX stale scenario is healthy before injecting worker failure")
(setq host-rx-fail t)
(def host-wait-start (systime))
(loopwhile (< (secs-since host-wait-start) 0.3) (sleep 0.01))
(test-check (and (> (secs-since rv-seen) 0.1)
                 (or (not host-has-diag)
                     (and (= diag-first 5) (> diag-rx-age 0.1) (< diag-rx-age 1.0))))
            "initialized RX later stalls and still trips unchanged 100ms watchdog")
(test-check (and (= safety-fault 12) (= park-on 1) (= host-current 0))
            "real post-startup RX loss still latches PARK and zero output")
(test-check (= (ride-set-park 0) 12) "real RX loss still refuses PARK exit")
(test-finish)
