(sleep 0.2)
(ride-select-mode 1)
(test-check (and (= current-profile 1) (= rv-seen-release 1) (= safety-fault 0))
            "Mode2 selected with healthy released RX input")
(test-check (< (abs (- host-min-speed-value (/ 3.0 3.6))) 0.0001)
            "reverse config sends 3kmh magnitude in m/s to official min-speed API")
; Firmware min-speed converts magnitude to negative ERPM; this host verifies
; the requested value only, never actual speed limiting or physical rotation.
(setq host-rx 0)
(setq host-adc1 1.0)
(sleep 0.4)
(test-check (and (= park-on 1) (= rv-armed 0) (= (ride-safety-state) 0))
            "PARK rejects reverse arming despite held RX and brake")
(setq host-rx 1)
(sleep 0.15)
(test-check (= (ride-set-park 0) 0) "healthy Mode2 exits PARK after releasing RX")
(sleep 0.1)
(test-check (and (= rv-btn 0) (= rv-dir 1) (= (ride-safety-state) 1)
                 (= current-profile 1) (= rv-brake-ticks 0))
            "hardware symptom: brake1 plus RX button0 stays forward Mode2")
(setq rm-rev-en 0)
(setq host-rx 0)
(sleep 0.4)
(test-check (and (= rv-btn 1) (= rv-armed 0) (= rv-dir 1))
            "disabled reverse remains forward despite RX press and brake")
(setq rm-rev-en 1)
(setq host-adc1 0.0)
(sleep 0.15)
(test-check (and (= rv-btn 1) (= rv-armed 0) (= rv-dir 0) (= (ride-safety-state) 4))
            "RX press without decoded brake enters INTERLOCK rather than staying Mode2")
(setq host-speed 0.5)
(setq host-adc1 1.0)
(sleep 0.4)
(test-check (and (= rv-armed 0) (= rv-dir 0))
            "moving vehicle cannot newly arm reverse")
(setq host-speed 0.0)
(sleep 0.4)
(test-check (and (= rv-armed 1) (>= rv-brake-ticks 20) (= (ride-safety-state) 2))
            "stopped idle throttle plus held RX and brake arms reverse")
(setq host-adc1 0.0)
; Wait for the actual brake ramp to decay, then apply throttle.
(sleep 0.8)
(setq host-adc0 0.4)
(sleep 0.3)
(test-check (and (= rv-dir -1) (= rv-armed 1) (= (ride-safety-state) 3))
            "releasing brake with RX held enters active reverse")
(test-check (and (eq host-current-kind 'absolute) (< host-current 0)
                 (>= host-current -7.0) (= host-current-delay 0.2))
            "actual motor loop commands bounded negative amps with optional off-delay")
(print (list 'reverse-output host-current host-current-delay rv-dir rv-armed))
(setq host-range-ok nil)
(sleep 0.05)
(test-check (and (= safety-fault 12) (= host-current 0) (= park-on 1) (= rv-armed 0))
            "fault during reverse clears authorization and commands zero")
(test-finish)
