; Assert the last command API, never interpret a historical current as active.
(sleep 0.2)
(test-check (= (ride-set-park 0) 0) "brake scenario exits healthy PARK")
(setq host-rx 0)
(setq host-adc1 1.0)
(sleep 0.6)
(test-check (and (= rv-armed 1) (= (ride-safety-state) 2)
                 (eq host-current-kind 'brake) (> host-brake 0))
            "armed reverse still commands braking while decoded brake is held")
(setq host-adc0 0.5)
(sleep 0.3)
(test-check (and (= rv-armed 1) (eq host-current-kind 'brake)
                 (> host-brake 0.9) (= rv-rel 0))
            "persistent brake ADC1 overrides throttle without creating reverse current")
(setq host-adc1 0.0)
(sleep 0.03)
(test-check (and (> brk-rel 0) (eq host-current-kind 'brake))
            "brake release initially retains its configured decay ramp")
(sleep 0.9)
(test-check (and (<= brk-rel 0.001) (= rv-dir -1)
                 (eq host-current-kind 'absolute) (< host-current 0))
            "after brake ramp decays held throttle commands reverse current")
(def host-before-brake rv-rel)
(setq host-adc1 1.0)
(sleep 0.05)
(test-check (and (eq host-current-kind 'brake) (> host-brake 0)
                 (< rv-rel host-before-brake))
            "reapplying brake replaces drive command and decays reverse ramp")
(sleep 0.7)
(test-check (and (= rv-rel 0) (eq host-current-kind 'brake))
            "sustained brake removes residual reverse ramp")
(setq host-adc0 0.0)
(setq host-adc1 0.0)
(sleep 0.9)
(test-check (and (= rv-armed 1) (<= brk-rel 0.001)
                 (eq host-current-kind 'absolute) (= host-current 0))
            "release with throttle zero commands zero despite retained reverse authorization")
(setq host-adc0 0.3)
(sleep 0.3)
(test-check (and (eq host-current-kind 'absolute) (< host-current 0)
                 (>= host-current -2.101))
            "subsequent reverse command follows current throttle rather than old ramp")
(test-check (= safety-fault 0) "brake transitions keep all workers healthy")
(test-finish)
