(sleep 0.2)
(test-check (= rm-rev-en 0) "reverse-disabled fixture loads saved reverse setting")
(test-check (and (= safety-fault 0) (= diag-first 0) (= motor-live 1))
            "reverse-disabled startup remains healthy with pending RX read")
(test-check (and (= rv-hw-ok 0) (= rv-armed 0))
            "disabled reverse cannot publish readiness or arm before its first sample")
(setq host-rx-release t)
(sleep 0.15)
(test-check (and (= rv-hw-ok 1) (= safety-fault 0) (= rv-armed 0))
            "disabled reverse stays unarmed after healthy RX initialization")
(test-finish)
