; Fresh interpreter/source load with saved native ADC Current (1), not NONE.
; The input conflict must remain a visible refusal, never bypass a drive gate.
(sleep 0.2)
(test-check (and (= motor-live 1) (= tx-live 1))
            "native Current conflict does not kill workers")
(test-check (and (not (native-input-only)) (= safety-fault 12)
                 (= park-on 1) (= host-current 0))
            "native Current reaches latched INPUT_FAULT and zero propulsion")
(send (test-event-pid) (cons 'event-data-rx [0x56 0x50 0x02 12 11 0 0 3 232]))
(sleep 0.1)
(test-check (= current-profile 0) "native Current blocks UI mode change")
(setq host-tx 0)
(sleep 0.15)
(setq host-tx 1)
(sleep 0.15)
(test-check (= current-profile 0) "native Current blocks hardware mode button")
(test-check (= (ride-set-park 0) 12) "native Current blocks PARK exit")
(setq host-adc0 0.8)
(sleep 0.05)
(test-check (= host-current 0) "native Current fault suppresses held throttle")
(safety-query 12 4660)
(test-check (and (= (bufget-u8 host-last-send 6) 5)
                 (= (bufget-u8 host-last-send 8) 12))
            "native Current safety poll reports INPUT_FAULT")
(rm-send-status-seq 12 4660)
(test-check (= (bufget-u8 host-last-send 18) 12)
            "native Current mode status reports INPUT_FAULT")
(setq host-adc-type 0)
(setq host-adc0 0.0)
(sleep 0.05)
(test-check (and (= safety-fault 12) (= (ride-set-park 0) 12))
            "changing config back to NONE does not silently clear drive fault")
(test-finish)
