; Run after the unmodified source, including @const-start/end and all spawns.
(sleep 0.2)
(test-check (= motor-live 1) "motor worker survives real VM startup")
(test-check (= tx-live 1) "TX worker survives real VM startup")
(test-check (= rv-hw-ok 1) "RX worker survives real VM startup")
(test-check (= safety-fault 0) "healthy ADC NONE reaches no input fault")
(test-check (native-input-only) "native-input-only executes actual trap/match")
(test-check (rm-try-reverse-speed 1 30) "supported min-speed trap succeeds")
(setq host-min-speed-ok nil)
(test-check (not (rm-try-reverse-speed 1 30)) "unsupported min-speed is contained by trap")
(setq host-min-speed-ok t)
(send (test-event-pid) (cons 'event-data-rx [0x56 0x50 0x01 12]))
(sleep 0.1)
(test-check (and (= (bufget-u8 host-last-send 2) 0x81)
                 (= (bufget-u8 host-last-send 4) 4))
            "real panel event thread returns Park plus three modes")
(send (test-event-pid) (cons 'event-data-rx [0x56 0x50 0x02 12 11 0 0 3 232]))
(sleep 0.1)
(test-check (and (= current-profile 1) (= park-on 1)
                 (= (bufget-u8 host-last-send 2) 0x82))
            "PARK permits mode 2 through real panel event and STATE reply")
(send (test-event-pid) (cons 'event-data-rx [0x56 0x50 0x02 12 12 0 0 3 232]))
(sleep 0.1)
(test-check (= current-profile 2) "PARK permits mode 3 through real panel event")
(setq host-adc0 0.8)
(sleep 0.05)
(test-check (= host-current 0) "PARK suppresses held throttle with running motor worker")
(setq host-adc0 0.0)
(sleep 0.05)
(test-check (= (ride-set-park 0) 0) "idle healthy worker can exit PARK")
(setq host-tx 0)
; Host Windows sleeps may round 10 ms up to the system timer quantum.
; Allow more than five samples; this is no assertion of the ESC's tick rate.
(sleep 0.15)
(setq host-tx 1)
(sleep 0.15)
(test-check (= current-profile 0) "real TX monitor cycles mode on debounced release")
(setq host-range-ok nil)
(sleep 0.05)
(test-check (and (= safety-fault 12) (= park-on 1) (= host-current 0)) "ADC range failure latches PARK and zero output")
(send (test-event-pid) (cons 'event-data-rx [0x56 0x50 0x02 12 12 0 0 3 232]))
(sleep 0.1)
(test-check (= current-profile 0) "fault refuses mode selection")
(safety-query 12 4660)
(test-check (and (= (buflen host-last-send) 9)
                 (= (bufget-u8 host-last-send 6) 5)
                 (= (bufget-u8 host-last-send 8) 12))
            "fault safety poll carries INPUT_FAULT instead of OK")
(rm-send-status-seq 12 4660)
(test-check (and (= (buflen host-last-send) 19)
                 (= (bufget-u8 host-last-send 18) 12))
            "fault sequenced status carries INPUT_FAULT instead of OK")
(setq host-range-ok t)
(sleep 0.05)
(test-check (and (= safety-fault 12) (= (ride-set-park 0) 12))
            "recovered ADC does not silently clear latched drive fault")
(test-finish)
